@startuml Q2-With-Strategy
left to right direction

Zookeeper "1" - "*" Animal
Animal "1" - "1" Roamer : strategy >
Runner -up|> Roamer
Stalker -up|> Roamer
Stomper -up|> Roamer

Zookeeper : {field} +Animal[] animalsList
Zookeeper : +main()
Zookeeper : +wakeAnimals()
Zookeeper : +feedAnimals()
Zookeeper : +letAnimalsRoam()
Zookeeper : +rollCallAnimals()
Zookeeper : +putAnimalsToBed()

Animal : {field} #string name
Animal : {field} #Roamer roamer
Animal : +Sleep()
Animal : +Wakeup()
Animal : +Roam()
Animal : {abstract} Eat()
Animal : {abstract} makeNoise()

Roamer : {abstract} roam()

Runner : +roam()
Stalker : +roam()
Stomper : +roam()

Canine -down|> Animal
Feline -down|> Animal
Pachyderm -down|> Animal

Dog -|> Canine
Wolf -|> Canine

Cat -|> Feline
Lion -|> Feline
Tiger -|> Feline

Elephant -|> Pachyderm
Hippo -|> Pachyderm
Rhino -|> Pachyderm

Dog : +eat()
Dog : +makeNoise()

Wolf : +eat()
Wolf : +makeNoise()

Cat : +eat()
Cat : +makeNoise()
Cat : +makeNoiseCat()
Cat : +randomBehavior()

Lion : +eat()
Lion : +makeNoise()

Tiger : +eat()
Tiger : +makeNoise()

Elephant : +eat()
Elephant : +makeNoise()

Hippo : +eat()
Hippo : +makeNoise()

Rhino : +eat()
Rhino : +makeNoise()


@enduml