@startuml Q2-With-Strategy


Zookeeper --> Animals : Wake Animals

Zookeeper --> Animals : Roll call Animals

Zookeeper --> Animals : Feed Animals

Zookeeper --> Animals : Let Animals roam
Animals --> Roamer : Call Roamer functionality

Zookeeper --> Animals : Put animals to bed


@enduml